all: testytest

testytest:
	$ g++ -std=c++11 -o testytest continuedTest.cpp continuedStudent.cpp 
gradygrade:
	$ g++ -std=c++11 -o gradygrade continuedGrading.cpp continuedStudent.cpp 

clean: 
	rm -rf *.o testytest gradygrade
