all: testytest

testytest:
	$ g++ -std=c++11 -o testytest gardensTest.cpp gardensStudent.cpp gardens.h

gradygrade:
	$ g++ -std=c++11 -o gradygrade gardensGrading.cpp gardensStudent.cpp flowers.h

clean: 
	rm -rf *.o testytest gradygrade
